#!/usr/bin/env perl
use strict;
use warnings;
use utf8;
use open ":utf8";

my $input = $ARGV[0];

open(DATAFILE, ">", "$input.pm") or die("error :$!");


print DATAFILE "package $input\n";
while (<DATA>) {
	print DATAFILE;
}

close(DATAFILE);

__DATA__
use strict;
use warnings;


1;
